services:
  - type: web
    name: n8n-self-host
    env: docker
    repo: https://github.com/Oyoo225/n8n-self-host
    branch: main
    dockerContext: ./n8n-self-host-starter
    dockerfilePath: ./n8n-self-host-starter/Dockerfile
    autoDeploy: true
