# render.yaml

services:
  - type: web
    name: n8n-self-host
    env: docker
    repo: https://github.com/Oyoo225/n8n-self-host
    branch: main
    
   
    dockerContext: .
    dockerfilePath: ./Dockerfile
    
    autoDeploy: true
    
    
    startCommand: /usr/local/bin/n8n start

    
    envVars:
      - key: GENERIC_TIMEZONE
        value: Asia/Bangkok
      - key: N8N_HOST
        value: n8n-self-host-0xgw.onrender.com 
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      
      
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false 
